# Generated by Django 6.0.4 on 2026-05-03 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='note',
        ),
        migrations.AddField(
            model_name='ticket',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='ticket',
            name='title',
            field=models.CharField(default='', max_length=200),
        ),
    ]
