# Generated by Django 6.0.4 on 2026-05-04 00:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0005_chatmessage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduleentry',
            name='created_by',
            field=models.CharField(default='manual', max_length=50),
        ),
        migrations.AddField(
            model_name='scheduleentry',
            name='locked',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='AgentConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent_type', models.CharField(max_length=50, unique=True)),
                ('priority', models.IntegerField(unique=True)),
                ('user', models.OneToOneField(limit_choices_to={'profile__role': 'ops'}, on_delete=django.db.models.deletion.CASCADE, related_name='agent_config', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['priority'],
            },
        ),
        migrations.CreateModel(
            name='AgentState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('deliberating', 'Deliberating'), ('committed', 'Committed')], default='deliberating', max_length=20)),
                ('document', models.TextField(blank=True, default='')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='states', to='tickets.agentconfig')),
                ('engineer', models.ForeignKey(limit_choices_to={'profile__role': 'engineer'}, on_delete=django.db.models.deletion.CASCADE, related_name='agent_states', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('engineer', 'config')},
            },
        ),
    ]
